services:
  app_api:
    container_name: app_api
    image: app_api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:8080"
    env_file:
      - ../queenbee/.env
      - ../beekeeper/.env
    depends_on:
      app_api_database:
        condition: service_healthy
    environment:
      - APP_API_DATABASE_URL=postgresql://app_api:app_api@app_api_database:5432/app_api
    mem_limit: 1g
    cpus: "2.0"

  app_api_database:
    image: postgres:18
    container_name: app_api_database
    restart: always
    environment:
      POSTGRES_USER: app_api
      POSTGRES_PASSWORD: app_api
      POSTGRES_DB: app_api
    volumes:
      - app_api_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_api -d app_api"]
      interval: 5s
      retries: 5
    mem_limit: 1g
    cpus: "2.0"

volumes:
  app_api_postgres_data:
