const OkRedFlagDealBreaker = [
    {
        id: 0,
        title_no: "Partneren din nekter å kjøpe angrepille.",
        title_en: "Your partner refuses to buy the morning pill.",
        categories: ["Party", "Wild"],
    },
    {
        id: 1,
        title_no: "Kjæresten din vil ha trekant.",
        title_en: "Your partner wants a threesome.",
        categories: ["Party", "Wild"],
    },
    {
        id: 2,
        title_no: "Kjæresten din snoker i meldingene dine.",
        title_en: "Your partner snoops in your messages.",
        categories: ["Party"],
    },
    {
        id: 3,
        title_no: "Kjæresten din nekter å gjøre husarbeid.",
        title_en: "Your partner refuses to do chores.",
        categories: ["Party"],
    },
    {
        id: 4,
        title_no: "Kjæresten din nekter å få seg en jobb.",
        title_en: "Your partner refuses to get a job.",
        categories: ["Party"],
    },
    {
        id: 5,
        title_no: "Kjæresten din nekter å betale regningene.",
        title_en: "Your partner refuses to pay the bills.",
        categories: ["Party"],
    },
    {
        id: 6,
        title_no: "Kjæresten din lyver om hvor de er.",
        title_en: "Your partner lies about where they are.",
        categories: ["Party"],
    },
    {
        id: 7,
        title_no: "Kjæresten din har en hemmelig mobiltelefon.",
        title_en: "Your partner has a secret phone.",
        categories: ["Party"],
    },
    {
        id: 8,
        title_no: "Kjæresten din kliner med andre på fest.",
        title_en: "Your partner makes out with others at parties.",
        categories: ["Party", "Wild"],
    },
    {
        id: 9,
        title_no: "Kjæresten din fester hver helg.",
        title_en: "Your partner parties every weekend.",
        categories: ["Party"],
    },
    {
        id: 10,
        title_no: "Kjæresten din mister alltid kontrollen på fylla.",
        title_en: "Your partner always loses control when drunk.",
        categories: ["Party"],
    },
    {
        id: 11,
        title_no: "Kjæresten din har en voldelig fortid.",
        title_en: "Your partner has a violent past.",
        categories: ["Party"],
    },
    {
        id: 12,
        title_no: "Kjæresten din røyker i skjul.",
        title_en: "Your partner smokes in secret.",
        categories: ["Party"],
    },
    {
        id: 13,
        title_no: "Kjæresten din drikker i skjul.",
        title_en: "Your partner drinks in secret.",
        categories: ["Party"],
    },
    {
        id: 14,
        title_no: "Kjæresten din tar narkotika.",
        title_en: "Your partner takes drugs.",
        categories: ["Party", "Wild"],
    },
    {
        id: 15,
        title_no: "Kjæresten din bruker alle pengene sine på gambling.",
        title_en: "Your partner spends all their money on gambling.",
        categories: ["Party"],
    },
    {
        id: 16,
        title_no: "Kjæresten din har en hemmelig bankkonto.",
        title_en: "Your partner has a secret bank account.",
        categories: ["Party"],
    },
    {
        id: 17,
        title_no: "Kjæresten din snakket fortsatt med eksen.",
        title_en: "Your partner still talks to their ex.",
        categories: ["Party"],
    },
    {
        id: 18,
        title_no: "Kjæresten din svarer aldri på meldingene dine når de er ute.",
        title_en: "Your partner never answers your messages when they're out.",
        categories: ["Party"],
    },
    {
        id: 19,
        title_no: "Kjæresten din kjører i fylla.",
        title_en: "Your partner drives drunk.",
        categories: ["Party", "Wild"],
    },
    {
        id: 20,
        title_no: "Kjæresten din spyr alltid i taxien på vei hjem fra byen.",
        title_en: "Your partner always throws up in the taxi on the way home from town.",
        categories: ["Party"],
    },
    {
        id: 21,
        title_no: "Kjæresten din stjeler alltid fra deg.",
        title_en: "Your partner always steals from you.",
        categories: ["Party"],
    },
    {
        id: 22,
        title_no: "Kjæresten din stjeler alltid et skilt på vei hjem fra byen.",
        title_en: "Your partner always steals a sign on the way home from town.",
        categories: ["Party"],
    },
    {
        id: 23,
        title_no: "Hvis de bruker tennis sko uten sokker.",
        title_en: "If they wear tennis shoes without socks.",
        categories: ["Party"],
    },
    {
        id: 24,
        title_no: "Hvis de aldri bruker sko.",
        title_en: "If they never wear shoes.",
        categories: ["Party"],
    },
    {
        id: 25,
        title_no: "Hvis de har en bestevenn av motsatt kjønn.",
        title_en: "If they have a best friend of the opposite gender.",
        categories: ["Party"],
    },
    {
        id: 26,
        title_no: "Hvis de har en mat instagram.",
        title_en: "If they have a food instagram.",
        categories: ["Party"],
    },
    {
        id: 27,
        title_no: "Hvis de har en trenings instagram.",
        title_en: "If they have a fitness instagram.",
        categories: ["Party"],
    },
    {
        id: 28,
        title_no: "Hvis de allerede har mer enn 3 kjæledyr.",
        title_en: "If they already have more than 3 pets.",
        categories: ["Party"],
    },
    {
        id: 29,
        title_no: "Hvis de kun har gammelt slitt eller hullete undertøy.",
        title_en: "If they only have old worn out or raggedy underwear.",
        categories: ["Party"],
    },
    {
        id: 30,
        title_no: "Hvis de har dårlig ordforråd.",
        title_en: "If they have a poor vocabulary.",
        categories: ["Party"],
    },
    {
        id: 31,
        title_no: "Hvis de er vegetarianer.",
        title_en: "If they are a vegetarian.",
        categories: ["Party"],
    },
    {
        id: 32,
        title_no: "Hvis de har en rar stemme.",
        title_en: "If they have a weird voice.",
        categories: ["Party"],
    },
    {
        id: 33,
        title_no: "Hvis de har mer enn 10 tatoveringer.",
        title_en: "If they have more than 10 tattoos.",
        categories: ["Party"],
    },
    {
        id: 34,
        title_no: "De er fortsatt god venn med eksen.",
        title_en: "They are still good friends with their ex.",
        categories: ["Party"],
    },
    {
        id: 35,
        title_no: "De er obsessed med konspirasjonsteorier.",
        title_en: "They are obsessed with conspiracy theories.",
        categories: ["Party"],
    },
    {
        id: 36,
        title_no: "De pusser ikke tennene hver dag.",
        title_en: "They don't brush their teeth every day.",
        categories: ["Party"],
    },
    {
        id: 37,
        title_no: "De klapper alltid når flyet lander.",
        title_en: "They always clap when the plane lands.",
        categories: ["Party"],
    },
    {
        id: 38,
        title_no: "De tror ikke på klimaendringer.",
        title_en: "They don't believe in climate change.",
        categories: ["Party"],
    },
    {
        id: 39,
        title_no: "De tror ikke på jubileum.",
        title_en: "They don't believe in anniversaries",
        categories: ["Party"],
    },
    {
        id: 40,
        title_no: "De tror ikke på vaksiner.",
        title_en: "They don't believe in vaccines.",
        categories: ["Party"],
    },
    {
        id: 41,
        title_no: "De hater hunder.",
        title_en: "They hate dogs.",
        categories: ["Party"],
    },
    {
        id: 42,
        title_no: "De tygger med åpen munn.",
        title_en: "They chew with their mouth open.",
        categories: ["Party"],
    },
    {
        id: 43,
        title_no: "Røyker hasj hele tiden.",
        title_en: "Smokes weed all the time.",
        categories: ["Party", "Wild"],
    },
    {
        id: 44,
        title_no: "Pusser tennene i dusjen.",
        title_en: "Brushes their teeth in the shower.",
        categories: ["Party"],
    },
    {
        id: 45,
        title_no: "Har en android.",
        title_en: "They have an android.",
        categories: ["Party"],
    },
    {
        id: 46,
        title_no: "Daten din sier 'ah' etter å ha tatt en slurk kaffe.",
        title_en: "Your Date Says 'Ah' After Sipping Coffee.",
        categories: ["Party"],
    },
    {
        id: 47,
        title_no: "Daten din er over 30, men bor fortsatt i kollektiv.",
        title_en: "Your date is older than 30 and still has several roommates.",
        categories: ["Party"],
    },
    {
        id: 48,
        title_no: "Har mer enn 20 kosedyr på rommet sitt.",
        title_en: "Has more than 20 stuffed animals in their room.",
        categories: ["Party"],
    },
    {
        id: 49,
        title_no: "Er en ginger.",
        title_en: "Is a ginger.",
        categories: ["Party"],
    },
    {
        id: 50,
        title_no: "Har øredobber.",
        title_en: "Has ear piercings.",
        categories: ["Party"],
    },
    {
        id: 51,
        title_no: "Har mindre enn gjennomsnittlig stor pikk.",
        title_en: "Has a smaller than average dick.",
        categories: ["Party", "Wild"],
    },
    {
        id: 52,
        title_no: "Bruker forkortelser når de snakker.",
        title_en: "Uses acronymns when they talk.",
        categories: ["Party"],
    },
    {
        id: 53,
        title_no: "Dere liker veldig forskjellig type sex.",
        title_en: "If you like very different types of sex.",
        categories: ["Party", "Wild"],
    },
    {
        id: 54,
        title_no: "Snakker under hele filmen.",
        title_en: "Talks the entire movie.",
        categories: ["Party"],
    },
]

const categories = ["Party", "Wild"]

export { categories }
export default OkRedFlagDealBreaker
