const Questions = [
    {
        id: 0,
        title_no: "Hvem har de mest absurde teoriene?",
        title_en: "Who has the most absurd theories?",
        categories: ["Party"],
    },
    {
        id: 1,
        title_no: "Hvem spilte tetris hver time på videregående?",
        title_en: "Who played tetris every class in high school?",
        categories: ["Gaming", "Party"],
    },
    {
        id: 2,
        title_no: "Hvem kommer alltid for sent?",
        title_en: "Who is always late?",
        categories: ["Party"],
    },
    {
        id: 3,
        title_no: "Hvem burde gå ut og lufte seg litt og røre gress?",
        title_en: "Who should go out and get some fresh air and touch grass?",
        categories: ["Gaming", "Party"],
    },
    {
        id: 4,
        title_no: "Hvem er den største romantikeren?",
        title_en: "Who is the biggest romantic?",
        categories: ["Party"],
    },
    {
        id: 5,
        title_no: "Hvem er den mest kreative?",
        title_en: "Who is the most creative?",
        categories: ["Party"],
    },
    {
        id: 6,
        title_no: "Hvem sklir på isen og tryner på vei til skolen?",
        title_en: "Who slips on the ice and falls on the way to school?",
        categories: ["Party"],
    },
    {
        id: 7,
        title_no: "Største Gen Z?",
        title_en: "Biggest Gen Z?",
        categories: ["Party"],
    },
    {
        id: 8,
        title_no: "Hvem må fortsatt vise leg på butikken?",
        title_en: "Who still has to show ID at the store?",
        categories: ["Party"],
    },
    {
        id: 9,
        title_no: "Hvem planlegger hybelen sin i Sims?",
        title_en: "Who plans their apartment in Sims?",
        categories: ["Party"],
    },
    {
        id: 10,
        title_no: "Hvem møter alltid opp til forelesningen?",
        title_en: "Who always shows up to the lecture?",
        categories: ["Party", "School"],
    },
    {
        id: 11,
        title_no: "Hvem elsker fargene til NTNUI?",
        title_en: "Who loves the colors of NTNUI?",
        categories: ["Party", "School", "NTNU"],
    },
    {
        id: 12,
        title_no: "Hvem ville du IKKE vært fanga på en øde øy med?",
        title_en: "Who would you NOT want to be stranded on a deserted island with?",
        categories: ["Party"],
    },
    {
        id: 13,
        title_no: "Hvem er den beste kokken?",
        title_en: "Who is the best chef?",
        categories: ["Party"],
    },
    {
        id: 14,
        title_no: "Hvem sovner på vors?",
        title_en: "Who falls asleep at vorspiel?",
        categories: ["Party"],
    },
    {
        id: 15,
        title_no: "Hvem spammer emojis som en 14 år gammel jente?",
        title_en: "Who abuses emojis like a 14 year old girl?",
        categories: ["Party"],
    },
    {
        id: 16,
        title_no: "Hvem skal delta på et realityprogram?",
        title_en: "Who will participate in a reality show?",
        categories: ["Party"],
    },
    {
        id: 17,
        title_no: "Hvem er forelska i det dårligste programmeringsspråket?",
        title_en: "Who is in love with the worst programming language?",
        categories: ["Party", "School", "NTNU"],
    },
    {
        id: 18,
        title_no: "Hvem hoster flest vors? Hosten deler ut 3 slurker.",
        title_en: "Who hosts vorspiel most often? The host gives out 3 sips",
        categories: ["Party"],
    },
    {
        id: 19,
        title_no: "Hvem får alltid tak i ekstra bonger?",
        title_en: "Who always gets extra free drinks?",
        categories: ["Party"],
    },
    {
        id: 20,
        title_no: "Hvem er ett akademisk offer?",
        title_en: "Who is an academic sacrifice?",
        categories: ["Party", "School"],
    },
    {
        id: 21,
        title_no: "Hvem ligger alltid bakpå med obliger?",
        title_en: "Who is always behind with assignments?",
        categories: ["Party", "School"],
    },
    {
        id: 22,
        title_no: "Hvem har den rareste hobbyen?",
        title_en: "Who has the weirdest hobby?",
        categories: ["Party"],
    },
    {
        id: 23,
        title_no: "Hvem er dårligst i beer pong?",
        title_en: "Who is the worst at beer pong?",
        categories: ["Party"],
    },
    {
        id: 24,
        title_no: "Hvem har mest hvit monster i blodet?",
        title_en: "Who has the most white monster in their blood?",
        categories: ["Party"],
    },
    {
        id: 25,
        title_no: "Hvem svarer aldri på meldinger?",
        title_en: "Who never answers messages?",
        categories: ["Party"],
    },
    {
        id: 26,
        title_no: "Hvem svarer på spørsmål på StackOverflow?",
        title_en: "Who answers questions on StackOverflow?",
        categories: ["Party", "School"],
    },
    {
        id: 27,
        title_no: "Hvem spør alltid om å queue på vors?",
        title_en: "Who always asks to queue at vorspiel?",
        categories: ["Party"],
    },
    {
        id: 28,
        title_no: "Hvem har bedriftsrepresentantene rundt lillefingeren?",
        title_en: "Who has the company representatives around their little finger?",
        categories: ["Party", "School"],
    },
    {
        id: 29,
        title_no: "Hvem gir deg høyest blodtrykk?",
        title_en: "Who gives you the highest blood pressure?",
        categories: ["Party"],
    },
    {
        id: 30,
        title_no: "Hvem har den beste sjekkereplikken? (Prøv den på personen til venstre)",
        title_en: "Who has the best pick-up line? (Try it on the person to your left)",
        categories: ["Party"],
    },
    {
        id: 31,
        title_no: "Hvem blir alltid kastet ut fra Huset?",
        title_en: "Who always gets kicked out of Huset?",
        categories: ["Party", "NTNU"],
    },
    {
        id: 32,
        title_no: "Hvem bruker fortsatt kalkulatoren på 14+15?",
        title_en: "Who still uses the calculator on 14+15?",
        categories: ["Party"],
    },
    {
        id: 33,
        title_no: "Hvem kunne kysset noen for en drink på byen?",
        title_en: "Who would kiss someone for a drink at the bar?",
        categories: ["Party"],
    },
    {
        id: 34,
        title_no: "Hvem drar aldri til forelesningene?",
        title_en: "Who never goes to class?",
        categories: ["Party", "School"],
    },
    {
        id: 35,
        title_no: "Hvem er alltid på jobb?",
        title_en: "Who is always at work?",
        categories: ["Party"],
    },
    {
        id: 36,
        title_no: "Hvem er kronisk hang? På 2-dagers allerede eller?",
        title_en: "Who is chronically hungover? On day 2 already?",
        categories: ["Party"],
    },
    {
        id: 37,
        title_no: "Hvem har fått flest prikker?",
        title_en: "Who has the most points on their license?",
        categories: ["Party"],
    },
    {
        id: 38,
        title_no: "Hvem finner de beste memesa på LL?",
        title_en: "Who finds the best memes on LL?",
        categories: ["Party", "School", "NTNU"],
    },
    {
        id: 39,
        title_no: "Hvem har LED striper over hele rommet sitt?",
        title_en: "Who has LED strips all over their room?",
        categories: ["Party"],
    },
    {
        id: 40,
        title_no: "Hvem ser Wolf of Wall Street hver dag som 'Pensum' i sigma grindset?",
        title_en: "Who watches Wolf of Wall Street every day as 'Curriculum' in sigma grindset?",
        categories: ["Party"],
    },
    {
        id: 41,
        title_no: "Hvem er alltid i kantina?",
        title_en: "Who is always in the canteen?",
        categories: ["Party"],
    },
    {
        id: 42,
        title_no: "Hvem bruker alltid light mode?",
        title_en: "Who always uses light mode?",
        categories: ["Party"],
    },
    {
        id: 43,
        title_no: "Hvem legger alltid ut for alle når de egentlig er blakk?",
        title_en: "Who always pays for everyone when they're actually broke?",
        categories: ["Party"],
    },
    {
        id: 44,
        title_no: "Hvem har de dårligste comebacksa?",
        title_en: "Who has the worst comebacks?",
        categories: ["Party"],
    },
    {
        id: 45,
        title_no: "Hvem er flinkest til å diskutere? Diskuter deg til en shot!!",
        title_en: "Who is the best at arguing? Argue your way to a shot!!",
        categories: ["Party"],
    },
    {
        id: 46,
        title_no: "Hvem klager på at eksamen gikk dritt, men får alltid bra karakter?",
        title_en: "Who complains that the exam went bad, but always gets a good grade?",
        categories: ["Party", "School"],
    },
    {
        id: 47,
        title_no: "Hvem er best i Mario Kart?",
        title_en: "Who is the best at Mario Kart?",
        categories: ["Party", "Gaming"],
    },
    {
        id: 48,
        title_no: "Hvem bruker Reddit AITA til å stille spørsmål om livet sitt?",
        title_en: "Who uses Reddit AITA to ask questions about their life?",
        categories: ["Party"],
    },
    {
        id: 49,
        title_no: "Hvem stjeler alltid skilt på fylla?",
        title_en: "Who always steals signs when drunk?",
        categories: ["Party"],
    },
    {
        id: 50,
        title_no: "Hvem stjeler alltid fra kantina?",
        title_en: "Who always steals from the canteen?",
        categories: ["Party"],
    },
    {
        id: 51,
        title_no: "Hvem forsvinner først på Huset?",
        title_en: "Who disappears first at Huset?",
        categories: ["Party", "School", "NTNU"],
    },
    {
        id: 52,
        title_no: "Hvem konter mest?",
        title_en: "Who re-sits the most?",
        categories: ["Party", "School", "NTNU"],
    },
    {
        id: 53,
        title_no: "Hvem har sagt at de er syk til jobben siden de var slitne?",
        title_en: "Who has called in sick because they were tired?",
        categories: ["Party", "School", "NTNU"],
    },
    {
        id: 54,
        title_no: "Hvem tror at jorden er flat?",
        title_en: "Who thinks the earth is flat?",
        categories: ["Party"],
    },
    {
        id: 55,
        title_no: "Hvem har de sykeste trick shotsa?",
        title_en: "Who has the sickest trick shots?",
        categories: ["Party"],
    },
    {
        id: 56,
        title_no: "Hvem spiller mest League?",
        title_en: "Who plays the most League?",
        categories: ["Party"],
    },
    {
        id: 57,
        title_no: "Hvem burde bli cancelled?",
        title_en: "Who should be cancelled?",
        categories: ["Party"],
    },
    {
        id: 58,
        title_no: "Hvem har de mest kreative roastene?",
        title_en: "Who has the most creative roasts?",
        categories: ["Party"],
    },
    {
        id: 59,
        title_no: "Hvem prøver å rømme fra politiet? (hvis de blir tatt)",
        title_en: "Who tries to escape from the police? (if they get caught)",
        categories: ["Party"],
    },
    {
        id: 60,
        title_no: "Hvem har lengst streak på Duolingo?",
        title_en: "Who has the longest streak on Duolingo?",
        categories: ["Party"],
    },
    {
        id: 61,
        title_no: "Hvem sin kode fungerer alltid uansett hvor dårlig den ser ut?",
        title_en: "Who's code always works no matter how bad it looks?",
        categories: ["Party", "School"],
    },
    {
        id: 62,
        title_no: "Hvem sover aldri i sin egen seng etter en kveld på byen?",
        title_en: "Who never sleeps in their own bed after a night out?",
        categories: ["Party"],
    },
    {
        id: 63,
        title_no: "Hvem er mest keen på å være fadder?",
        title_en: "Who is most keen on being a buddy (fadder)?",
        categories: ["Party", "School"],
    },
    {
        id: 64,
        title_no: "Hvem begynner heller med OnlyFans hvis de stryker Algmet igjen?",
        title_en: "Who would rather start an OnlyFans if they fail Algmet again?",
        categories: ["Party", "School", "NTNU"],
    },
    {
        id: 65,
        title_no: "Hvem er best i Smash?",
        title_en: "Who is the best at Smash?",
        categories: ["Party"],
    },
    {
        id: 66,
        title_no: "Hvem er med på alt?",
        title_en: "Who is up for anything?",
        categories: ["Party"],
    },
    {
        id: 67,
        title_no: "Hvem faller først i bakken på skitur?",
        title_en: "Who falls first on a ski trip?",
        categories: ["Party"],
    },
    {
        id: 68,
        title_no: "Hvem ender alltid opp på Heim?",
        title_en: "Who always ends up at Heim?",
        categories: ["Party", "NTNU"],
    },
    {
        id: 69,
        title_no: "Største boomer?",
        title_en: "Biggest boomer?",
        categories: ["Party"],
    },
    {
        id: 70,
        title_no: "Hvem har en uforklarlig evne til å alltid finne veien hjem, uansett hvor borte de er?",
        title_en: "Who has an inexplicable ability to always find their way home, no matter how lost they are?",
        categories: ["Party"],
    },
    {
        id: 71,
        title_no: "Hvem trenger ikke vise leg til vekterne på byen? (siden de alltid er der)",
        title_en: "Who doesn't need to show ID to the bouncers at the bar? (since they're always there)",
        categories: ["Party"],
    },
    {
        id: 72,
        title_no: "Hvem kunne vært Cheerleader i en American High School film?",
        title_en: "Who could have been a cheerleader in an American High School movie?",
        categories: ["Party", "School"],
    },
    {
        id: 73,
        title_no: "Hvem bruker mer tid på Netflix enn på skole?",
        title_en: "Who spends more time on Netflix than on school?",
        categories: ["Party", "School"],
    },
    {
        id: 74,
        title_no: "Hvem kunne startet den neste store crypto scammen?",
        title_en: "Who could start the next big crypto scam?",
        categories: ["Party"],
    },
    {
        id: 75,
        title_no: "Hvem sitt storstipend forsvinner på mystisk vis hver semesterstart?",
        title_en: "Whose large scholarship mysteriously disappears every semester start?",
        categories: ["Party", "School"],
    },
    {
        id: 76,
        title_no: "Hvem har alltid en ekstra powerbank?",
        title_en: "Who always has an extra power bank?",
        categories: ["Party"],
    },
    {
        id: 77,
        title_no: "Hvem har den VERSTE drinken? (kanskje noen kan gi tips)",
        title_en: "Who has the WORST drink? (maybe someone can give tips)",
        categories: ["Party"],
    },
    {
        id: 78,
        title_no: "Hvem ville du helst hatt med på en øde øy?",
        title_en: "Who would you rather have with you on a deserted island?",
        categories: ["Party"],
    },
    {
        id: 79,
        title_no: "Hvem er din 'partner in crime' for øvinger og gruppearbeid?",
        title_en: "Who is your 'partner in crime' for studying and group work?",
        categories: ["Party"],
    },
    {
        id: 80,
        title_no: "Hvem er alltid syk?",
        title_en: "Who is always ill?",
        categories: ["Party"],
    },
    {
        id: 81,
        title_no: "Hvem bruker Passord123 som passord?",
        title_en: "Who uses Password123 as their password?",
        categories: ["Party"],
    },
    {
        id: 82,
        title_no: "Hvem er best venn med GPT?",
        title_en: "Who is best friends with GPT?",
        categories: ["Party", "School"],
    },
    {
        id: 83,
        title_no: "Hvem behandler GPT som om den var en ekte person med følelser?",
        title_en: "Who treats GPT as if it were a real person with feelings?",
        categories: ["Party"],
    },
    {
        id: 84,
        title_no: "Hvem blir nekta adgang på byen?",
        title_en: "Who gets denied entry to the bar?",
        categories: ["Party"],
    },
    {
        id: 85,
        title_no: "Hvem er den største karaoke-stjerna?",
        title_en: "Who is the biggest karaoke star?",
        categories: ["Party"],
    },
    {
        id: 86,
        title_no: "Hvem har alltid en (ikke nødvendigvis god) plan på byen?",
        title_en: "Who always has a (not necessarily good) plan at the bar?",
        categories: ["Party"],
    },
    {
        id: 87,
        title_no: "Hvem er alltid på mobilen?",
        title_en: "Who is always on their phone?",
        categories: ["Party"],
    },
    {
        id: 88,
        title_no: "Hvem har mest viljestyrke?",
        title_en: "Who has the most willpower?",
        categories: ["Party"],
    },
    {
        id: 89,
        title_no: "Hvem vil ha trekant?",
        title_en: "Who wants a threesome?",
        categories: ["Party", "Wild"],
    },
    {
        id: 90,
        title_no: "Er best på å chugge?",
        title_en: "Is the best at chugging?",
        categories: ["Party"],
    },
    {
        id: 91,
        title_no: "Er dårligst sjåfør?",
        title_en: "Is the worst driver?",
        categories: ["Party"],
    },
    {
        id: 92,
        title_no: "Er mest vill?",
        title_en: "Is the wildest?",
        categories: ["Party", "Wild"],
    },
    {
        id: 93,
        title_no: "Spanderer alltid på fylla?",
        title_en: "Always pays for drinks?",
        categories: ["Party"],
    },
    {
        id: 94,
        title_no: "Er kåtest?",
        title_en: "Is the horniest?",
        categories: ["Party", "Wild"],
    },
    {
        id: 95,
        title_no: "Er flinkest på skolen?",
        title_en: "Is the best at school?",
        categories: ["Party"],
    },
    {
        id: 96,
        title_no: "Tar seg mest på puppene?",
        title_en: "Always touches their boobs?",
        categories: ["Party", "Wild"],
    },
    {
        id: 97,
        title_no: "Tror fortsatt på julenissen?",
        title_en: "Still believes in Santa Claus?",
        categories: ["Party"],
    },
    {
        id: 98,
        title_no: "Mest ubesluttsom?",
        title_en: "Who is the most indecisive?",
        categories: ["Party"],
    },
    {
        id: 99,
        title_no: "Har høyest promille?",
        title_en: "Has the highest blood alcohol level?",
        categories: ["Party"],
    },
    {
        id: 100,
        title_no: "Hvem er mest sannsynlig til å bli statsminister?",
        title_en: "Who is most likely to become prime minister?",
        categories: ["Party"],
    },
    {
        id: 101,
        title_no: "Er mest rettferdig?",
        title_en: "Is the most fair?",
        categories: ["Party"],
    },
    {
        id: 102,
        title_no: "Blir mest sannsynlig millionær?",
        title_en: "Is the most likely to become a millionaire?",
        categories: ["Party"],
    },
    {
        id: 103,
        title_no: "Hvem vil man ikke havne på gruppe med?",
        title_en: "Who do you not want to end up in a group assignment with?",
        categories: ["Party", "School"],
    },
    {
        id: 104,
        title_no: "Lager de sykeste lydene i senga?",
        title_en: "Makes the wildest noises in bed?",
        categories: ["Party"],
    },
    {
        id: 105,
        title_no: "Er mest overlegen?",
        title_en: "Is the most arrogant?",
        categories: ["Party"],
    },
    {
        id: 106,
        title_no: "Hvem kommer til å lykkes best i livet?",
        title_en: "Who will succeed the most in life?",
        categories: ["Party"],
    },
    {
        id: 107,
        title_no: "Trener mest?",
        title_en: "Trains the most?",
        categories: ["Party"],
    },
    {
        id: 108,
        title_no: "Gir mest penger til veldedighet?",
        title_en: "Donates the most money to charity?",
        categories: ["Party"],
    },
    {
        id: 109,
        title_no: "Er lykkeligst?",
        title_en: "Is the happiest?",
        categories: ["Party"],
    },
    {
        id: 110,
        title_no: "Googler seg selv oftest?",
        title_en: "Googles themselves the most?",
        categories: ["Party"],
    },
    {
        id: 111,
        title_no: "Er den verste stalkeren?",
        title_en: "Is the worst stalker?",
        categories: ["Party"],
    },
    {
        id: 112,
        title_no: "Har dårligst musikksmak?",
        title_en: "Has the worst taste in music?",
        categories: ["Party"],
    },
    {
        id: 113,
        title_no: "Kommer til å sovne med kebaben i hånda?",
        title_en: "Will fall asleep with the kebab in their hand?",
        categories: ["Party"],
    },
    {
        id: 114,
        title_no: "Har shavet og er forberedt på alt?",
        title_en: "Has shaved and is prepared for anything?",
        categories: ["Party"],
    },
    {
        id: 115,
        title_no: "Har høyest body count?",
        title_en: "Has the highest body count?",
        categories: ["Party", "Wild"],
    },
    {
        id: 116,
        title_no: "Er sterkest?",
        title_en: "Is the strongest?",
        categories: ["Party"],
    },
    {
        id: 117,
        title_no: "Kommer mest sannsynlig til å spy i kveld?",
        title_en: "Will most likely throw up tonight?",
        categories: ["Party"],
    },
    {
        id: 118,
        title_no: "Har finest dialekt?",
        title_en: "Has the nicest dialect?",
        categories: ["Party"],
    },
    {
        id: 119,
        title_no: "Havner på gata?",
        title_en: "Will end up on the street?",
        categories: ["Party"],
    },
    {
        id: 120,
        title_no: "Lyser opp rommet?",
        title_en: "Lights up the room?",
        categories: ["Party"],
    },
    {
        id: 121,
        title_no: "Skiller seg mest ut i mengden?",
        title_en: "Stands out the most in the crowd?",
        categories: ["Party"],
    },
    {
        id: 122,
        title_no: "Har størst kjendisfaktor?",
        title_en: "Has the biggest celebrity factor?",
        categories: ["Party"],
    },
    {
        id: 123,
        title_no: "Er mest eventyrlysten?",
        title_en: "Is the most adventurous?",
        categories: ["Party"],
    },
    {
        id: 124,
        title_no: "Snorker mest?",
        title_en: "Snores the most?",
        categories: ["Party"],
    },
    {
        id: 125,
        title_no: "Slipper de verste fisene?",
        title_en: "Lets out the worst farts?",
        categories: ["Party"],
    },
    {
        id: 126,
        title_no: "Kunne levd best med bare en arm og ett ben?",
        title_en: "Could have lived best with only one arm and one leg?",
        categories: ["Party"],
    },
    {
        id: 127,
        title_no: "Løper fortest?",
        title_en: "Runs the fastest?",
        categories: ["Party"],
    },
    {
        id: 128,
        title_no: "Kommer til å gifte seg først?",
        title_en: "Will get married first?",
        categories: ["Party"],
    },
    {
        id: 129,
        title_no: "Hvem er medlem av Mile High Club?",
        title_en: "Who is a member of the Mile High Club?",
        categories: ["Party"],
    },
    {
        id: 130,
        title_no: "Kommer til å bli rikest?",
        title_en: "Will become the richest?",
        categories: ["Party"],
    },
    {
        id: 131,
        title_no: "Kommer til å havne i fengsel?",
        title_en: "Will end up in prison?",
        categories: ["Party"],
    },
    {
        id: 132,
        title_no: "Gir best strippeshow?",
        title_en: "Gives the best strip show?",
        categories: ["Party"],
    },
    {
        id: 133,
        title_no: "Tar med seg noen hjem i kveld?",
        title_en: "Takes someone home tonight?",
        categories: ["Party"],
    },
    {
        id: 134,
        title_no: "Rir best?",
        title_en: "Rides the best?",
        categories: ["Party", "Wild"],
    },
    {
        id: 135,
        title_no: "Bor finest?",
        title_en: "Lives in the nicest place?",
        categories: ["Party"],
    },
    {
        id: 136,
        title_no: "Tar flest selfies?",
        title_en: "Takes the most selfies?",
        categories: ["Party"],
    },
    {
        id: 137,
        title_no: "Kommer raskest?",
        title_en: "Cums the fastest?",
        categories: ["Party", "Wild"],
    },
    {
        id: 138,
        title_no: "Har lettest for å bryte isen med noen ukjente?",
        title_en: "Is the best at breaking the ice with strangers?",
        categories: ["Party"],
    },
    {
        id: 139,
        title_no: "Kommer mest sannsynlig til å stryke et fag dette semesteret?",
        title_en: "Will most likely fail a course this semester?",
        categories: ["Party", "School"],
    },
    {
        id: 140,
        title_no: "Er mest sporty?",
        title_en: "Is the sportiest?",
        categories: ["Party"],
    },
    {
        id: 141,
        title_no: "Lager best stemning på vors?",
        title_en: "Creates the best vibe at vorspiel?",
        categories: ["Party"],
    },
    {
        id: 142,
        title_no: "Har de peneste øyene?",
        title_en: "Has the prettiest eyes?",
        categories: ["Party"],
    },
    {
        id: 143,
        title_no: "Er best i senga?",
        title_en: "Is the best in bed?",
        categories: ["Party"],
    },
    {
        id: 144,
        title_no: "Er mest drita?",
        title_en: "Is the most drunk?",
        categories: ["Party"],
    },
    {
        id: 145,
        title_no: "Har best karakterer?",
        title_en: "Has the best grades?",
        categories: ["Party"],
    },
    {
        id: 146,
        title_no: "Er den svetteste gameren?",
        title_en: "Is the sweatiest gamer?",
        categories: ["Party"],
    },
    {
        id: 147,
        title_no: "Har best sjanse til å overleve mot en bjørn?",
        title_en: "Has the best chance of surviving against a bear?",
        categories: ["Party"],
    },
    {
        id: 148,
        title_no: "Kler briller best?",
        title_en: "Suits glasses best?",
        categories: ["Party"],
    },
    {
        id: 149,
        title_no: "Er snillest?",
        title_en: "Is the nicest?",
        categories: ["Party"],
    },
    {
        id: 150,
        title_no: "Er mest klar for arbeidslivet?",
        title_en: "Is the most ready for working life?",
        categories: ["Party"],
    },
    {
        id: 151,
        title_no: "Har flest blonde øyeblikk?",
        title_en: "Has the most blonde moments?",
        categories: ["Party"],
    },
    {
        id: 152,
        title_no: "Har mest temperament?",
        title_en: "Has the most temper?",
        categories: ["Party"],
    },
    {
        id: 153,
        title_no: "Holder på med flere samtidig?",
        title_en: "Is seeing multiple people at once?",
        categories: ["Party", "Wild"],
    },
    {
        id: 154,
        title_no: "Selv tror den er morsomst?",
        title_en: "Thinks they're the funniest?",
        categories: ["Party"],
    },
    {
        id: 155,
        title_no: "Har hatt flest kjærester?",
        title_en: "Has had the most boyfriends/girlfriends?",
        categories: ["Party"],
    },
    {
        id: 156,
        title_no: "Er en liten luremus?",
        title_en: "Is a little trickster?",
        categories: ["Party", "Wild"],
    },
    {
        id: 157,
        title_no: "Har verst musikksmak?",
        title_en: "Has the worst taste in music?",
        categories: ["Party"],
    },
    {
        id: 158,
        title_no: "Har mest humørsvingninger?",
        title_en: "Has the most mood swings?",
        categories: ["Party"],
    },
    {
        id: 159,
        title_no: "Synger styggest?",
        title_en: "Sing the ugliest?",
        categories: ["Party"],
    },
    {
        id: 160,
        title_no: "Har mest kroppshår?",
        title_en: "Has the most body hair?",
        categories: ["Party"],
    },
    {
        id: 161,
        title_no: "Er tøffest i trynet?",
        title_en: "Thinks they're the toughest?",
        categories: ["Party"],
    },
    {
        id: 162,
        title_no: "Har finest lepper?",
        title_en: "Has the nicest lips?",
        categories: ["Party"],
    },
    {
        id: 163,
        title_no: "Har den mest skitne nettleserhistorikken?",
        title_en: "Has the dirtiest browser history?",
        categories: ["Party", "Wild"],
    },
    {
        id: 164,
        title_no: "Er best kjent i byen dere er i?",
        title_en: "Is best known in the city you're in?",
        categories: ["Party"],
    },
    {
        id: 165,
        title_no: "Hvem har vært flest ganger på legevakten det siste året?",
        title_en: "Who has been to the ER the most times in the last year?",
        categories: ["Party"],
    },
    {
        id: 166,
        title_no: "Hadde gjort det best på skal vi danse?",
        title_en: "Would have done the best on 'shall we dance'?",
        categories: ["Party"],
    },
    {
        id: 167,
        title_no: "Kunne du aldri hatt med i et familieselskap?",
        title_en: "Could you never bring to a family gathering?",
        categories: ["Party"],
    },
    {
        id: 168,
        title_no: "Tåler smerte best?",
        title_en: "Has the highest pain tolerance?",
        categories: ["Party"],
    },
    {
        id: 169,
        title_no: "Driter seg alltid ut?",
        title_en: "Always embarrasses themselves?",
        categories: ["Party"],
    },
    {
        id: 170,
        title_no: "Er flinkest til å sjekke opp på byen?",
        title_en: "Is the best at picking up at the bar?",
        categories: ["Party"],
    },
    {
        id: 171,
        title_no: "Er mest spontan?",
        title_en: "Is the most spontaneous?",
        categories: ["Party"],
    },
    {
        id: 172,
        title_no: "Tror på synske?",
        title_en: "Believes in psychics?",
        categories: ["Party"],
    },
    {
        id: 173,
        title_no: "Har kortest telefonsamtaler?",
        title_en: "Has the shortest phone calls?",
        categories: ["Party"],
    },
    {
        id: 174,
        title_no: "Har størst lommebok?",
        title_en: "Has the biggest wallet?",
        categories: ["Party"],
    },
    {
        id: 175,
        title_no: "Ser på mest reality-drit?",
        title_en: "Watches the most reality crap?",
        categories: ["Party"],
    },
    {
        id: 176,
        title_no: "Har tatt kongla flest ganger?",
        title_en: "Has taken the cone the most times?",
        categories: ["Party", "Wild"],
    },
    {
        id: 177,
        title_no: "Har størst føtter?",
        title_en: "Has the biggest feet?",
        categories: ["Party"],
    },
    {
        id: 178,
        title_no: "Er mest mystisk?",
        title_en: "Is the most mysterious?",
        categories: ["Party"],
    },
    {
        id: 179,
        title_no: "Minner mest om en ape?",
        title_en: "Resembles an ape the most?",
        categories: ["Party"],
    },
    {
        id: 180,
        title_no: "Har hatt flest kjønnssjukdommer?",
        title_en: "Has had the most STDs?",
        categories: ["Party", "Wild"],
    },
    {
        id: 181,
        title_no: "Tar alltid en for laget?",
        title_en: "Always takes one for the team?",
        categories: ["Party"],
    },
    {
        id: 182,
        title_no: "Er mest frekk i kjeften?",
        title_en: "Is the most cheeky?",
        categories: ["Party"],
    },
    {
        id: 183,
        title_no: "Skal chugge sammen med deg?",
        title_en: "Will chug with you?",
        categories: ["Party"],
    },
    {
        id: 184,
        title_no: "Ville du helst presentert for foreldrene dine?",
        title_en: "Would you rather introduce to your parents?",
        categories: ["Party"],
    },
    {
        id: 185,
        title_no: "Prøver seg på den eldste i kveld?",
        title_en: "Tries to get with the oldest tonight?",
        categories: ["Party"],
    },
    {
        id: 186,
        title_no: "Har mest skitne tanker?",
        title_en: "Has the dirtiest thoughts?",
        categories: ["Party", "Wild"],
    },
    {
        id: 187,
        title_no: "Har pult den eldste?",
        title_en: "Has fucked the oldest?",
        categories: ["Party", "Wild"],
    },
    {
        id: 188,
        title_no: "Er lengst i dusjen?",
        title_en: "Takes the longest showers?",
        categories: ["Party"],
    },
    {
        id: 189,
        title_no: "Er klar for å få barn?",
        title_en: "Is ready to have children?",
        categories: ["Party"],
    },
    {
        id: 190,
        title_no: "Liker å bruke buttplug?",
        title_en: "Likes to wear a buttplug?",
        categories: ["Party", "Wild"],
    },
    {
        id: 191,
        title_no: "Kommer til å flytte hjem igjen til foreldrene sine?",
        title_en: "Will move back to their parents again?",
        categories: ["Party"],
    },
    {
        id: 192,
        title_no: "Jukser mest?",
        title_en: "Cheats the most?",
        categories: ["Party", "School"],
    },
    {
        id: 193,
        title_no: "Har de mest spennende brystene?",
        title_en: "Has the most appealing breasts?",
        categories: ["Party", "Wild"],
    },
    {
        id: 194,
        title_no: "Kler seg best?",
        title_en: "Dresses the best?",
        categories: ["Party"],
    },
    {
        id: 195,
        title_no: "Snuser mest?",
        title_en: "Snuses the most?",
        categories: ["Party"],
    },
    {
        id: 196,
        title_no: "Bruker mest penger på alkohol?",
        title_en: "Spends the most money on alcohol?",
        categories: ["Party"],
    },
    {
        id: 197,
        title_no: "Bruker mest penger på gambling?",
        title_en: "Spends the most money on gambling?",
        categories: ["Party", "Gaming"],
    },
    {
        id: 198,
        title_no: "Er en skikkelig sofagris?",
        title_en: "Is a real couch potato?",
        categories: ["Party"],
    },
    {
        id: 199,
        title_no: "Tar mest initiativ i sengen?",
        title_en: "Takes the most initiative in bed?",
        categories: ["Party", "Wild"],
    },
    {
        id: 200,
        title_no: "Er mest gjerrig?",
        title_en: "Is the most stingy?",
        categories: ["Party"],
    },
    {
        id: 201,
        title_no: "Vil du helst ha med på en roadtrip?",
        title_en: "Would you rather bring on a road trip?",
        categories: ["Party"],
    },
    {
        id: 202,
        title_no: "Hvem har du ett lite øye for?",
        title_en: "Do you have a little crush on?",
        categories: ["Party"],
    },
    {
        id: 203,
        title_no: "Hvem hadde flest anmerkninger på ungdomsskolen?",
        title_en: "Who had the most remarks in middle school?",
        categories: ["Party", "School"],
    },
    {
        id: 204,
        title_no: "Har den sjukeste latteren?",
        title_en: "Has the craziest laugh?",
        categories: ["Party"],
    },
    {
        id: 205,
        title_no: "Er minst skoleflink?",
        title_en: "Is the least good at school?",
        categories: ["Party", "School"],
    },
    {
        id: 206,
        title_no: "Har en liggeliste på notater?",
        title_en: "Has a list of hookups in notes?",
        categories: ["Party", "Wild"],
    },
    {
        id: 207,
        title_no: "Kunne spist mest sushi?",
        title_en: "Could have eaten the most sushi?",
        categories: ["Party"],
    },
    {
        id: 208,
        title_no: "Blir oftest tatt på fersken av foreldrene?",
        title_en: "Is most often caught by their parents?",
        categories: ["Party"],
    },
    {
        id: 209,
        title_no: "Er mest bortskjemt?",
        title_en: "Is the most spoiled?",
        categories: ["Party"],
    },
    {
        id: 210,
        title_no: "Har lyst å komme i buksen på noen i kveld?",
        title_en: "Want to get in someone's pants tonight?",
        categories: ["Party", "Wild"],
    },
    {
        id: 211,
        title_no: "Har minst føtter?",
        title_en: "Has the smallest feet?",
        categories: ["Party"],
    },
    {
        id: 211,
        title_no: "Blir raskest sjalu?",
        title_en: "Gets jealous the easiest?",
        categories: ["Party"],
    },
    {
        id: 212,
        title_no: "Er mest uskyldig?",
        title_en: "Is the most innocent?",
        categories: ["Party"],
    },
    {
        id: 213,
        title_no: "Blir gravid først?",
        title_en: "Gets pregnant first?",
        categories: ["Party", "Wild"],
    },
    {
        id: 214,
        title_no: "Er mest crazy?",
        title_en: "Is the most crazy?",
        categories: ["Party", "Wild"],
    },
    {
        id: 215,
        title_no: "Har finest legger?",
        title_en: "Has the nicest calves?",
        categories: ["Party"],
    },
    {
        id: 216,
        title_no: "Er morsomst?",
        title_en: "Is funniest?",
        categories: ["Party"],
    },
    {
        id: 217,
        title_no: "Hvem får du vakrest barn sammen med?",
        title_en: "Who would you have the most beautiful children with?",
        categories: ["Party"],
    },
    {
        id: 218,
        title_no: "Er dårligst på å bruke prevensjon?",
        title_en: "Is the worst at using contraception?",
        categories: ["Party", "Wild"],
    },
    {
        id: 219,
        title_no: "Har størst penis?",
        title_en: "Has the largest penis?",
        categories: ["Party", "Wild"],
    },
    {
        id: 220,
        title_no: "Er mest glad i pupper?",
        title_en: "Likes tits the most?",
        categories: ["Party", "Wild"],
    },
    {
        id: 221,
        title_no: "Er mest populær?",
        title_en: "Is the most popular?",
        categories: ["Party"],
    },
    {
        id: 222,
        title_no: "Har hatt flest orgasmer?",
        title_en: "Has had the most orgasms?",
        categories: ["Party", "Wild"],
    },
    {
        id: 223,
        title_no: "Er mest opptatt av utseende?",
        title_en: "Is the most concerned about their appearance?",
        categories: ["Party"],
    },
    {
        id: 224,
        title_no: "Er den største sossen?",
        title_en: "Is the biggest freak?",
        categories: ["Party"],
    },
    {
        id: 225,
        title_no: "Er frekkest?",
        title_en: "Is the rudest?",
        categories: ["Party"],
    },
    {
        id: 226,
        title_no: "Brukt falsk legitimasjon flest ganger?",
        title_en: "Has used fake ID the most?",
        categories: ["Party"],
    },
    {
        id: 227,
        title_no: "Har flest nakenbilder på telefonen sin?",
        title_en: "Has the most nudes on their phone?",
        categories: ["Party", "Wild"],
    },
    {
        id: 228,
        title_no: "Har flest filmer av seg selv på mobilen?",
        title_en: "Has the most videos of themselves on their phone?",
        categories: ["Party"],
    },
    {
        id: 229,
        title_no: "Har mest FOMO?",
        title_en: "Who has the most FOMO?",
        categories: ["Party"],
    },
    {
        id: 230,
        title_no: "Har det ryddigste rommet?",
        title_en: "Has the cleanest room?",
        categories: ["Party"],
    },
    {
        id: 231,
        title_no: "Har lengst tånegler?",
        title_en: "Has the longest toenails?",
        categories: ["Party"],
    },
    {
        id: 232,
        title_no: "Har blitt pumpa?",
        title_en: "Has been pumped?",
        categories: ["Party"],
    },
    {
        id: 233,
        title_no: "Spiller et instrument best?",
        title_en: "Plays an instrument the best?",
        categories: ["Party"],
    },
    {
        id: 234,
        title_no: "Debuterte først?",
        title_en: "Debuted first?",
        categories: ["Party"],
    },
    {
        id: 235,
        title_no: "Hatt seg i et telt?",
        title_en: "Have made out in a tent?",
        categories: ["Party"],
    },
    {
        id: 236,
        title_no: "Slutter på studiet først?",
        title_en: "Will drop out of school first?",
        categories: ["Party", "School"],
    },
    {
        id: 237,
        title_no: "Kunne vært en Hollywoodskuespiller?",
        title_en: "Could have been a Hollywood actor?",
        categories: ["Party"],
    },
    {
        id: 238,
        title_no: "Bruker minst penger på mat?",
        title_en: "Spend the least money on food?",
        categories: ["Party"],
    },
    {
        id: 239,
        title_no: "Er mest fornøyd med sitt eget utseende?",
        title_en: "Is the most satisfied with their own appearance?",
        categories: ["Party"],
    },
    {
        id: 240,
        title_no: "Blir pappa først?",
        title_en: "Will become a dad first?",
        categories: ["Party"],
    },
    {
        id: 241,
        title_no: "Spiser sunnest?",
        title_en: "Eats the healthiest?",
        categories: ["Party"],
    },
    {
        id: 242,
        title_no: "Prøver å bli Tik-Tok kjendis?",
        title_en: "Tries to become a Tik-Tok celebrity?",
        categories: ["Party"],
    },
    {
        id: 243,
        title_no: "Har flest følgere på Instagram?",
        title_en: "Has the most followers on Instagram?",
        categories: ["Party"],
    },
    {
        id: 244,
        title_no: "Mest religiøs?",
        title_en: "Is the most religious?",
        categories: ["Party"],
    },
    {
        id: 245,
        title_no: "Er høyest?",
        title_en: "Is the tallest?",
        categories: ["Party"],
    },
    {
        id: 246,
        title_no: "Har finest frisyre?",
        title_en: "Has the nicest hairstyle?",
        categories: ["Party"],
    },
    {
        id: 247,
        title_no: "Er eldst mentalt?",
        title_en: "Is the oldest mentally?",
        categories: ["Party"],
    },
    {
        id: 248,
        title_no: "Er yngst mentalt?",
        title_en: "Is the youngest mentally?",
        categories: ["Party"],
    },
    {
        id: 249,
        title_no: "Størst baller?",
        title_en: "Has the biggest balls?",
        categories: ["Party"],
    },
    {
        id: 250,
        title_no: "Kunne vært med på Paradise Hotel?",
        title_en: "Could have been on Paradise Hotel?",
        categories: ["Party"],
    },
    {
        id: 251,
        title_no: "Tåler mest alkohol?",
        title_en: "Tolerates alcohol the best?",
        categories: ["Party"],
    },
    {
        id: 252,
        title_no: "Er mest dedikert?",
        title_en: "Is the most dedicated?",
        categories: ["Party"],
    },
    {
        id: 253,
        title_no: "Drikker fortest?",
        title_en: "Drinks the fastest?",
        categories: ["Party"],
    },
    {
        id: 254,
        title_no: "Har finest smil?",
        title_en: "Has the prettiest smile?",
        categories: ["Party"],
    },
    {
        id: 255,
        title_no: "Er mest desperat?",
        title_en: "Is the most desperate?",
        categories: ["Party"],
    },
    {
        id: 256,
        title_no: "Er den største fylliken?",
        title_en: "Is the biggest drunkie?",
        categories: ["Party"],
    },
    {
        id: 257,
        title_no: "Har finest rumpe?",
        title_en: "Has the nicest butt?",
        categories: ["Party", "Wild"],
    },
    {
        id: 258,
        title_no: "Drar på flest Tinderdates?",
        title_en: "Goes on the most Tinder dates?",
        categories: ["Party"],
    },
    {
        id: 259,
        title_no: "Har hatt seg med flest nasjonaliteter?",
        title_en: "Have got together with the most nationalities?",
        categories: ["Party"],
    },
    {
        id: 260,
        title_no: "Spiser mest pasta?",
        title_en: "Eats the most pasta?",
        categories: ["Party"],
    },
    {
        id: 261,
        title_no: "Får kjeft av foreldrene oftest?",
        title_en: "Gets scolded by their parents the most?",
        categories: ["Party"],
    },
    {
        id: 262,
        title_no: "Får kjæreste i år?",
        title_en: "Will get a partner this year?",
        categories: ["Party"],
    },
    {
        id: 263,
        title_no: "Spruter mest?",
        title_en: "Squrits the most?",
        categories: ["Party", "Wild"],
    },
    {
        id: 264,
        title_no: "Kunne bodd på en øde øy frivillig?",
        title_en: "Could have lived on a deserted island voluntarily?",
        categories: ["Party"],
    },
    {
        id: 265,
        title_no: "Lukter best?",
        title_en: "Smells the best?",
        categories: ["Party"],
    },
    {
        id: 266,
        title_no: "Har vært festens midtpunkt?",
        title_en: "Has been the center of attention at the party?",
        categories: ["Party"],
    },
    {
        id: 267,
        title_no: "Hvem klarer ikke å holde på en hemmelighet?",
        title_en: "Who can't keep a secret?",
        categories: ["Party"],
    },
    {
        id: 268,
        title_no: "Hvem klarer ikke å stoppe å prate?",
        title_en: "Who can't stop talking?",
        categories: ["Party"],
    },
    {
        id: 269,
        title_no: "Bruker mest penger på drit?",
        title_en: "Spends the most money on crap?",
        categories: ["Party"],
    },
    {
        id: 270,
        title_no: "Legger mest an på folk?",
        title_en: "Hits on people the most?",
        categories: ["Party"],
    },
    {
        id: 271,
        title_no: "Har høyest IQ?",
        title_en: "Has the highest IQ?",
        categories: ["Party"],
    },
    {
        id: 272,
        title_no: "Bruker lengst tid på do?",
        title_en: "Spends the longest time in the bathroom?",
        categories: ["Party"],
    },
    {
        id: 273,
        title_no: "Viser mest takknemmelighet?",
        title_en: "Shows the most gratitude?",
        categories: ["Party"],
    },
    {
        id: 274,
        title_no: "Gjør minst husarbeid?",
        title_en: "Does the least housework?",
        categories: ["Party"],
    },
    {
        id: 275,
        title_no: "Snakker mest bullshit?",
        title_en: "Talks the most bullshit?",
        categories: ["Party"],
    },
    {
        id: 276,
        title_no: "Har de største drømmene, men er minst sannsynlig til å oppnå dem?",
        title_en: "Has the biggest dreams, but is least likely to achieve them?",
        categories: ["Party"],
    },
    {
        id: 277,
        title_no: "Mest pervers?",
        title_en: "Most perverted?",
        categories: ["Party", "Wild"],
    },
    {
        id: 278,
        title_no: "Har hatt flest sexpartnere det siste halvåret?",
        title_en: "Has had the most sexual partners in the last six months?",
        categories: ["Party", "Wild"],
    },
    {
        id: 279,
        title_no: "Har mest bein i nesa?",
        title_en: "Has the most guts?",
        categories: ["Party"],
    },
    {
        id: 280,
        title_no: "Har livet på stell?",
        title_en: "Has life in order?",
        categories: ["Party"],
    },
    {
        id: 281,
        title_no: "Best i sjakk?",
        title_en: "Best at chess?",
        categories: ["Party"],
    },
    {
        id: 282,
        title_no: "Sniker oftest i køer?",
        title_en: "Sneaks in lines the most?",
        categories: ["Party"],
    },
    {
        id: 283,
        title_no: "Må alltid på do?",
        title_en: "Always has to go to the bathroom?",
        categories: ["Party"],
    },
    {
        id: 284,
        title_no: "Mest shady?",
        title_en: "Most shady?",
        categories: ["Party"],
    },
    {
        id: 285,
        title_no: "Tjent mest det siste året?",
        title_en: "Earned the most in the last year?",
        categories: ["Party"],
    },
    {
        id: 286,
        title_no: "Har finest hjem?",
        title_en: "Has the nicest home?",
        categories: ["Party"],
    },
    {
        id: 287,
        title_no: "Har minst filter?",
        title_en: "Has the least filter?",
        categories: ["Party"],
    },
    {
        id: 288,
        title_no: "Mest usunn?",
        title_en: "Most unhealthy?",
        categories: ["Party"],
    },
    {
        id: 289,
        title_no: "Ville du aldri latt sitte barnevakt for ungen din?",
        title_en: "Would you never let babysit your child?",
        categories: ["Party"],
    },
    {
        id: 290,
        title_no: "Din trofaste fyllapartner?",
        title_en: "Your faithful drinking buddy?",
        categories: ["Party"],
    },
    {
        id: 291,
        title_no: "Har gjort mest sykt?",
        title_en: "Has done the craziest things?",
        categories: ["Party"],
    },
    {
        id: 292,
        title_no: "Ser best ut i undertøy?",
        title_en: "Looks best in underwear?",
        categories: ["Party"],
    },
    {
        id: 293,
        title_no: "Mest kresen?",
        title_en: "Most picky?",
        categories: ["Party"],
    },
    {
        id: 294,
        title_no: "Liker seg selv best?",
        title_en: "Likes themselves the most?",
        categories: ["Party"],
    },
    {
        id: 295,
        title_no: "Tar flest screen shots?",
        title_en: "Take the most screen shots?",
        categories: ["Party"],
    },
    {
        id: 296,
        title_no: "Kommer til å få barn først?",
        title_en: "Will have children first?",
        categories: ["Party"],
    },
    {
        id: 297,
        title_no: "Har mest flaks?",
        title_en: "Is the luckiest?",
        categories: ["Party"],
    },
    {
        id: 298,
        title_no: "Drar alltid hjem sist fra bye?",
        title_en: "Always comes home last from parties?",
        categories: ["Party"],
    },
    {
        id: 299,
        title_no: "Skal alltid på nach?",
        title_en: "Is always going to the nachspiel?",
        categories: ["Party"],
    },
    {
        id: 300,
        title_no: "Egentlig en indre villmann?",
        title_en: "Actually an inner savage?",
        categories: ["Party"],
    },
    {
        id: 301,
        title_no: "Hvem dusjer minst?",
        title_en: "Showers the least?",
        categories: ["Party"],
    },
    {
        id: 302,
        title_no: "Mest glad i kjæresten sin?",
        title_en: "Loves their partner the most?",
        categories: ["Party"],
    },
    {
        id: 303,
        title_no: "Snakker mest?",
        title_en: "Talks the most?",
        categories: ["Party"],
    },
    {
        id: 304,
        title_no: "Har mest livserfaring?",
        title_en: "Has the most life experience?",
        categories: ["Party"],
    },
    {
        id: 305,
        title_no: "Best i fotball?",
        title_en: "Best at soccer?",
        categories: ["Party"],
    },
    {
        id: 306,
        title_no: "Drar alltid hjem først fra byen?",
        title_en: "Always goes home first from the city?",
        categories: ["Party"],
    },
    {
        id: 307,
        title_no: "Blir fullest i kveld?",
        title_en: "Will get the most drunk tonight?",
        categories: ["Party"],
    },
    {
        id: 308,
        title_no: "Mest ærlig?",
        title_en: "Most honest?",
        categories: ["Party"],
    },
    {
        id: 309,
        title_no: "Har mest kontroll i fylla?",
        title_en: "Has the most control when drunk?",
        categories: ["Party"],
    },
    {
        id: 310,
        title_no: "Har minst kontroll i fylla?",
        title_en: "Has the least control when drunk?",
        categories: ["Party"],
    },
    {
        id: 311,
        title_no: "Blir raskest skremt?",
        title_en: "Gets scared the easiest?",
        categories: ["Party"],
    },
    {
        id: 312,
        title_no: "Er redd for edderkopper?",
        title_en: "Is afraid of spiders?",
        categories: ["Party"],
    },
    {
        id: 313,
        title_no: "Ville mest saynnsylig ofret livet for en totalt fremmed?",
        title_en: "Would most likely sacrifice their life for a total stranger?",
        categories: ["Party"],
    },
    {
        id: 314,
        title_no: "Har best forhold med foreldrene sine?",
        title_en: "Has the best relationship with their parents?",
        categories: ["Party"],
    },
    {
        id: 315,
        title_no: "Prater mest 🧢?",
        title_en: "Talks the most 🧢?",
        categories: ["Party"],
    },
    {
        id: 316,
        title_no: "Mest rastløs?",
        title_en: "Most restless?",
        categories: ["Party"],
    },
    {
        id: 317,
        title_no: "Sender flest meldinger på Tinder?",
        title_en: "Sends the most messages on Tinder?",
        categories: ["Party"],
    },
    {
        id: 318,
        title_no: "Har reist til flest land?",
        title_en: "Has traveled to the most countries?",
        categories: ["Party"],
    },
    {
        id: 319,
        title_no: "Brukt mest penger på take-away siste året?",
        title_en: "Has spent the most money on take-away in the last year?",
        categories: ["Party"],
    },
    {
        id: 320,
        title_no: "Hadde gjort det best på 71 Grader Nord?",
        title_en: "Would have done the best on 71 Degrees North?",
        categories: ["Party"],
    },
    {
        id: 321,
        title_no: "Er det mest typiske enebarnet?",
        title_en: "Is the most typical only child?",
        categories: ["Party"],
    },
    {
        id: 322,
        title_no: "Mest materialistisk?",
        title_en: "Most materialistic?",
        categories: ["Party"],
    },
    {
        id: 323,
        title_no: "Ser mest på TV?",
        title_en: "Watches the most TV?",
        categories: ["Party"],
    },
    {
        id: 324,
        title_no: "Har drukket minst hittil? (chug)",
        title_en: "Has drunk the least so far? (chug)",
        categories: ["Party"],
    },
    {
        id: 325,
        title_no: "Minst uskyldig?",
        title_en: "Least innocent?",
        categories: ["Party"],
    },
    {
        id: 326,
        title_no: "Stråler mest?",
        title_en: "Shines the most?",
        categories: ["Party"],
    },
    {
        id: 327,
        title_no: "Er på jakt etter en eldre kjæreste som betaler alt?",
        title_en: "Is looking for an older partner who pays for everything?",
        categories: ["Party"],
    },
    {
        id: 328,
        title_no: "Har lest flest bøker?",
        title_en: "Has read the most books?",
        categories: ["Party"],
    },
    {
        id: 329,
        title_no: "Har sendt inn flest bidrag til memekontoer på Insta?",
        title_en: "Has submitted the most contributions to meme accounts on Insta?",
        categories: ["Party"],
    },
    {
        id: 330,
        title_no: "Lager mest drama?",
        title_en: "Creates the most drama?",
        categories: ["Party"],
    },
    {
        id: 331,
        title_no: "Stjeler alltid noe på byen?",
        title_en: "Always steals something from the bar?",
        categories: ["Party"],
    },
    {
        id: 332,
        title_no: "Kunne blitt sammen med en person lengst unna egen alder?",
        title_en: "Could have been with a person furthest from their own age?",
        categories: ["Party", "Wild"],
    },
    {
        id: 333,
        title_no: "Kjøpte en angrepille sist?",
        title_en: "Bought a morning-after pill last?",
        categories: ["Party", "Wild"],
    },
    {
        id: 334,
        title_no: "Mest sannsynlig til å løpe maraton?",
        title_en: "Most likely to run a marathon?",
        categories: ["Party"],
    },
    {
        id: 335,
        title_no: "Er den største datanerden?",
        title_en: "Is the biggest computer nerd?",
        categories: ["Party"],
    },
    {
        id: 336,
        title_no: "Har flest ubetalte regninger?",
        title_en: "Has the most unpaid bills?",
        categories: ["Party"],
    },
    {
        id: 337,
        title_no: "Følger flest influencere på Insta?",
        title_en: "Follows the most influencers on Insta?",
        categories: ["Party"],
    },
    {
        id: 338,
        title_no: "Har best rettningssans?",
        title_en: "Has the best sense of direction?",
        categories: ["Party"],
    },
    {
        id: 339,
        title_no: "Har dårligst rettningssans?",
        title_en: "Has the worst sense of direction?",
        categories: ["Party"],
    },
    {
        id: 340,
        title_no: "Har en greie for føtter?",
        title_en: "Has a thing for feet?",
        categories: ["Party"],
    },
    {
        id: 341,
        title_no: "Har tatt fyllatattovering?",
        title_en: "Has taken a drunk tattoo?",
        categories: ["Party"],
    },
    {
        id: 342,
        title_no: "Ser seg mest i speilet?",
        title_en: "Looks at themselves the most in the mirror?",
        categories: ["Party"],
    },
    {
        id: 343,
        title_no: "Kunne ha solgt sjelen på Instagram for sponset treningstøy?",
        title_en: "Could have sold their soul on Instagram for sponsored workout clothes?",
        categories: ["Party"],
    },
    {
        id: 344,
        title_no: "Har hatt flest one night stands?",
        title_en: "Has had the most one night stands?",
        categories: ["Party"],
    },
    {
        id: 345,
        title_no: "Den største playeren?",
        title_en: "The biggest player?",
        categories: ["Party"],
    },
    {
        id: 346,
        title_no: "Kunne havnet på omg just dont?",
        title_en: "Could have ended up on omg just dont?",
        categories: ["Party"],
    },
    {
        id: 347,
        title_no: "Har mest penger?",
        title_en: "Has the most money?",
        categories: ["Party"],
    },
    {
        id: 348,
        title_no: "Kunne dumpet kjæresten over SMS?",
        title_en: "Could have dumped their partner over SMS?",
        categories: ["Party"],
    },
    {
        id: 349,
        title_no: "Er den mest utadvendte?",
        title_en: "Is the most outgoing?",
        categories: ["Party"],
    },
    {
        id: 350,
        title_no: "Har mest studiegjeld?",
        title_en: "Has the most student debt?",
        categories: ["Party", "School"],
    },
    {
        id: 351,
        title_no: "Har flest tørre vitser?",
        title_en: "Has the most dry jokes?",
        categories: ["Party"],
    },
    {
        id: 352,
        title_no: "Har brutt loven flest ganger?",
        title_en: "Has committed the most crimes?",
        categories: ["Party"],
    },
    {
        id: 353,
        title_no: "Har mest selvironi?",
        title_en: "Has the most self-irony?",
        categories: ["Party"],
    },
    {
        id: 354,
        title_no: "Har minst selvinnsikt?",
        title_en: "Has the least self-awareness?",
        categories: ["Party"],
    },
    {
        id: 355,
        title_no: "Har størst familie?",
        title_en: "Has the biggest family?",
        categories: ["Party"],
    },
    {
        id: 356,
        title_no: "Har det beste draget?",
        title_en: "Has the best game?",
        categories: ["Party"],
    },
    {
        id: 357,
        title_no: "Mest kosete?",
        title_en: "Most cuddly?",
        categories: ["Party"],
    },
    {
        id: 358,
        title_no: "Har dårligst humor?",
        title_en: "Has the worst humor?",
        categories: ["Party"],
    },
    {
        id: 359,
        title_no: "Spydde sist på fylla?",
        title_en: "Threw up last time drunk?",
        categories: ["Party"],
    },
    {
        id: 360,
        title_no: "Bruker mest tid på TikTok?",
        title_en: "Spends the most time on TikTok?",
        categories: ["Party"],
    },
    {
        id: 361,
        title_no: "Har mest klær?",
        title_en: "Has the most clothes?",
        categories: ["Party"],
    },
    {
        id: 362,
        title_no: "Har oftest fylleangst?",
        title_en: "Has the most hangover anxiety?",
        categories: ["Party"],
    },
    {
        id: 363,
        title_no: "Har hatt en one night stand med en kollega?",
        title_en: "Has had a one night stand with a colleague?",
        categories: ["Party", "Wild"],
    },
    {
        id: 364,
        title_no: "Har løyet om alderen sin?",
        title_en: "Has lied about their age?",
        categories: ["Party"],
    },
    {
        id: 365,
        title_no: "Hvem ville mest sannsynlig blitt med på en blind date?",
        title_en: "Who would most likely go on a blind date?",
        categories: ["Party"],
    },
    {
        id: 366,
        title_no: "Hvem ville mest sannsynlig fått sitt eget realityshow?",
        title_en: "Who would most likely get their own reality show?",
        categories: ["Party"],
    },
    {
        id: 367,
        title_no: "Har blitt kastet ut av en bar eller en klubb i år?",
        title_en: "Has been thrown out of a bar or club this year?",
        categories: ["Party"],
    },
    {
        id: 368,
        title_no: "Har hatt seg med noen utendørs?",
        title_en: "Has made love outdoors?",
        categories: ["Party", "Wild"],
    },
    {
        id: 369,
        title_no: "Hvem har hatt trekant?",
        title_en: "Who has had a threesome?",
        categories: ["Party", "Wild"],
    },
    {
        id: 370,
        title_no: "Har sendt nudes flest ganger?",
        title_en: "Has sent nudes the most times?",
        categories: ["Party", "Wild"],
    },
    {
        id: 371,
        title_no: "Er mest opptatt av andre sitt utseende?",
        title_en: "Is the most concerned about other people's appearance?",
        categories: ["Party"],
    },
    {
        id: 372,
        title_no: "Har spionert på en eks-kjæreste?",
        title_en: "Has spied on an ex-boyfriend?",
        categories: ["Party"],
    },
    {
        id: 373,
        title_no: "Gjør noe dumt i kveld?",
        title_en: "Does something stupid tonight?",
        categories: ["Party"],
    },
    {
        id: 374,
        title_no: "Mest sannsynlig til å sovne på jobb?",
        title_en: "Most likely to fall asleep at work?",
        categories: ["Party"],
    },
    {
        id: 375,
        title_no: "Har mest sminke i vesken?",
        title_en: "Has the most makeup in their bag?",
        categories: ["Party"],
    },
    {
        id: 376,
        title_no: "Har hatt seg med noen på en offentlig strand?",
        title_en: "Has made out with someone on a public beach?",
        categories: ["Party"],
    },
    {
        id: 377,
        title_no: "Hvem har ikke shavet, men likevel forberedt på alt?",
        title_en: "Who hasn't shaved, but still prepared for everything?",
        categories: ["Party"],
    },
    {
        id: 378,
        title_no: "Er den beste til å kysse?",
        title_en: "Is the best kisser?",
        categories: ["Party"],
    },
    {
        id: 379,
        title_no: "Har mest innlevelse i filmene de ser?",
        title_en: "Has the most empathy in the movies they watch?",
        categories: ["Party"],
    },
    {
        id: 380,
        title_no: "Ser mest på porno?",
        title_en: "Watches the most porn?",
        categories: ["Party", "Wild"],
    },
    {
        id: 381,
        title_no: "Fingrer mest?",
        title_en: "Fingers themselves the most often?",
        categories: ["Party"],
    },
    {
        id: 382,
        title_no: "Er mest fotogen?",
        title_en: "Is the most photogenic?",
        categories: ["Party"],
    },
    {
        id: 383,
        title_no: "Ser på The Kardashians?",
        title_en: "Watches The Kardashians?",
        categories: ["Party"],
    },
    {
        id: 384,
        title_no: "Hvem måtte ringe hjem fra skolen siden de gjorde noe galt?",
        title_en: "Who had to call home since they did something bad at school?",
        categories: ["Party", "School"],
    },
    {
        id: 385,
        title_no: "Hvem oppfører seg som de har mensen akkurat nå?",
        title_en: "Who behaves as if they have menstruation right now?",
        categories: ["Party", "Wild"],
    },
    {
        id: 386,
        title_no: "Hvem har onanert i dag?",
        title_en: "Who has masturbated today?",
        categories: ["Party", "Wild"],
    },
    {
        id: 387,
        title_no: "Hvem ville du helst hatt som tjener det neste døgnet?",
        title_en: "Who would you rather have as a servant for the next day?",
        categories: ["Party"],
    },
    {
        id: 388,
        title_no: "Hvem her er den beste vennen når det gjelder?",
        title_en: "Who here is the best friend when it comes to?",
        categories: ["Party"],
    },
    {
        id: 389,
        title_no: "Hvem her har på mest sexy undertøy akkurat nå?",
        title_en: "Who here is wearing the most sexy underwear right now?",
        categories: ["Party", "Wild"],
    },
]

const categories = ["Gaming", "Party", "School", "Wild", "NTNU"]

export { categories }
export default Questions
